### ISSUE TITLE
Add new object types

### ISSUE THREAD

**Issue by paralin** [eldarion-gondor/pykube#13]
We need "PersistentVolume", "PersistentVolumeClaim", and a few others, like "HorizontalScaler"

**Comment by brosner** [comment]
Agreed. We definitely need to expand the available objects. I am happy to accept PRs.

**Comment by pcm32** [comment]
Could we (@rjmw, @korseby and me) also request that you add the new "Job" object? Thanks!

**Comment by brosner** [comment]
@pcm32 absolutely. I can give it a look this week, but if you can send in a PR I can get it in even faster. Thanks for the request!

**Comment by pcm32** [comment]
Thanks @brosner, if you give us a few pointers on how the objects of the REST API from k8s are mimicked in your pykube, we would be glad to give it a go and generate a PR!

**Comment by brosner** [comment]
@pcm32 if you take a look at the recent addition of `Deployment` (relevant to `Job` due to being an extension) it should give you everything to produce a PR.

https://github.com/eldarion-gondor/pykube/pull/15/files

**Comment by korseby** [comment]
Wouldn't it be enough to add the following code to objects.py to add just the "jobs" object?

```
class Job(NamespacedAPIObject):

    version = "v1"
    endpoint = "jobs"
```

**Comment by brosner** [comment]
@korseby exactly right. However, I believe `Job` is in version `extensions/v1beta1`.

**Comment by brosner** [comment]
There have been many new objects added. I say this issue is no longer relavant. Thanks to everyone who has contributed a new object! Keep 'em coming.
