### ISSUE TITLE
List/Watch objects in all namespaces

### ISSUE THREAD

**Issue by jayme-github** [eldarion-gondor/pykube#23]
I want to query objects in all namespaces (`GET /api/v1/services` for example). What is the correct/intended way to do so (as `NamespacedAPIObject` always sets `DEFAULT_NAMESPACE` on instantiation)?

I see at least the following two possible ways:

Manually overwrite namespace in `ObjectManager` instance:
```py
serviceQuery = Service.objects(api)
serviceQuery.namespace = None # Query all namespaces
services = serviceQuery.all()
```

Create a "Non-namespaced" version of the object class:
```py
class Service(APIObject):
    version = 'v1'
    endpoint = 'services'

    @property
    def namespace(self):
        if self.obj['metadata'].get('namespace'):
            return self.obj['metadata']['namespace']

services = Service.objects(api).all()
```

**Comment by brosner** [comment]
To query all namespaces, you can use `pykube.all` value:

```
pykube.Service.objects(api).filter(namespace=pykube.all)
```

**Comment by jayme-github** [comment]
Thanks for your help!
