### ISSUE TITLE
Release for 1.2 Kubernetes?

### ISSUE THREAD

**Issue by cdrage** [eldarion-gondor/pykube#32]
Now that we've got all the features from 1.2 implemented into `pykube`, is it possible to do a (even minor) release of pykube so we can pull the new version from pip?

**Comment by brosner** [comment]
Yep, I plan on doing a release very soon. You can still install pykube with pip without a release. I don't like tracking an issue for a release so I am going to close this, but expect a release either later today or tomorrow morning at the latest.

**Comment by brosner** [comment]
v0.10.0 is up on PyPI. Enjoy!

**Comment by cdrage** [comment]
@brosner omg yes, thank you!
