### ISSUE TITLE
Example code fails to run with error "ObjectManager instance has no attribute 'endpoint'"

### ISSUE THREAD

**Issue by chrisleck** [eldarion-gondor/pykube#8]
```
>>> api = HTTPClient(KubeConfig.from_file("/Users/<username>/.kube/config"))
>>> pods = Pod.objects(api).filter(namespace="<a valid namespace>")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/src/experimental/build/krypton-virtualenv/lib/python2.7/site-packages/pykube/query.py", line 83, in __call__
    return Query(api, self.endpoint, self.api_obj_class, namespace=self.namespace)
AttributeError: ObjectManager instance has no attribute 'endpoint'
```

**Comment by brosner** [comment]
I admit my Python 2 testing is lacking. I will take a look.

**Comment by chrisleck** [comment]
My wild unsubstantiated guess is that it has something to do with the class inheritance and the __get__ handler on ObjectManager.

**Comment by brosner** [comment]
From my quick tests, it appears that `__get__` isn't being called at all.

**Comment by brosner** [comment]
Bah, I see the issue. I've spent too much time in Python 3 land and the cleaner `class MyClass:` (notice the lack of `object` base class) has spoiled me.

Fix incoming.

**Comment by brosner** [comment]
Meant to tag the issue in the commit. Fixed in 0fd135e37d299bd153012c709d74f3f108abee83.

**Comment by chrisleck** [comment]
Thanks for the ultra-fast turnaround!  Will this be auto-pushed for ```pip install --upgrade``` to pickup or do we need to do something additional?

**Comment by brosner** [comment]
I am happy to push out 0.6.1 for `pip` awesomeness. Give me a few minutes.

**Comment by brosner** [comment]
@chrisleck 0.6.1 is up on PyPI.

**Comment by chrisleck** [comment]
Confirmed this is working now with python 2.7.11.  Nice work!!
